version: '3'
services:
  ###
  # services
  ###

  # main app
  web:
    build: .
    network_mode: host
    command: gunicorn -k eventlet -w 1 --threads=5 project.wsgi:application --log-level=debug
    volumes:
        - .:/app
    ports:
        - "8000:8000"
    tty: true
    env_file:
      - ./.env
    stdin_open: true
  
  # celery worker
  worker:
      build: .
      depends_on:
        - rabbitmq
      network_mode: host
      command:  celery worker -A project -B --loglevel=INFO --concurrency=5
      env_file:
        - ./.env
      volumes:
        - .:/app

  # message broker
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    network_mode: host
