# Generated by Django 3.0.2 on 2020-03-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='values',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
    ]
