# Generated by Django 3.0.2 on 2020-03-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200329_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
